Downport no angular-js branch
hslayers/hslayers-ng pull request #1287
Opened 2020-11-23 12:54 UTC by raitisbe

2020-11-23 17:10 UTC, jmacura reviewed
I keep getting this error when compiling full example with this branch...
![image](https://user-images.githubusercontent.com/5598693/99992720-0325b500-2db7-11eb-834d-e6fcbe73261d.png)
Is some alignment to webpack config needed?

2020-11-23 18:09 UTC, jmacura requested changes

2020-11-23 18:13 UTC, jmacura commented
> 
> 
> I keep getting this error when compiling full example with this branch...
> Is some alignment to webpack config needed?

Made it work by adding
```
"esModuleInterop": true,
"resolveJsonModule": true
```
to the application's tsconfig.json.

2020-11-23 19:53 UTC, raitisbe commented on components/save-map/partials/simpleform.html
> -            <button type="button" class="btn btn-secondary" (click)="cancel()">{{'COMMON.cancel' | translate}}</button>
Yes, because could not test it and just wanted to compile. Dont even know what cancel is supposed to do here.

2020-11-23 19:55 UTC, raitisbe commented
> resolveJsonModule

Thanks, that flag we should have nevertheless.

2020-11-23 20:00 UTC, raitisbe commented on components/add-layers/partials/dialog_getcapabilities_error.html
>                  <button type="button" class="btn btn-secondary" ng-click="capabilitiesErrorModalVisible = false" data-dismiss="modal">{{'COMMON.close' | translate}}</button>
> And there are more non-upgraded directives in this template (ng-click, ng-class). Not sure if it is in active use...

Yes, Aot compiler doesn't spot those. Will have to have another sweep for angularjs attributes manuaaly at some time.

2020-11-23 21:44 UTC, jmacura commented on components/save-map/partials/simpleform.html
> -            <button type="button" class="btn btn-secondary" (click)="cancel()">{{'COMMON.cancel' | translate}}</button>
Me neither. I took a brief look at the UI and it doesn't seem to be useful to me.

2020-11-23 21:47 UTC, jmacura commented on components/add-layers/partials/dialog_getcapabilities_error.html
>                  <button type="button" class="btn btn-secondary" ng-click="capabilitiesErrorModalVisible = false" data-dismiss="modal">{{'COMMON.close' | translate}}</button>
No big deal. I tried to search for a "ng-" string and almost all remaining occurrences are in the MD files, with just a few exceptions.

2020-11-24 16:07 UTC, raitisbe commented on components/core/core.module.ts
> +import lv from '../../assets/locales/lv.json';
Done

2020-11-24 16:55 UTC, jmacura commented on components/add-layers/partials/dialog_getcapabilities_error.html
>                  <button type="button" class="btn btn-secondary" ng-click="capabilitiesErrorModalVisible = false" data-dismiss="modal">{{'COMMON.close' | translate}}</button>
What about this? Will you touch it in this PR or leave it for another one?

2020-11-24 17:48 UTC, raitisbe commented on components/add-layers/partials/dialog_getcapabilities_error.html
>                  <button type="button" class="btn btn-secondary" ng-click="capabilitiesErrorModalVisible = false" data-dismiss="modal">{{'COMMON.close' | translate}}</button>
Done

2020-11-25 14:21 UTC, jmacura approved these changes

2020-11-25 16:11 UTC, DailisLangovskis approved these changes

2020-11-25 16:15 UTC, FilipLeitner commented on components/layout/layout.component.ts
> +    if (this.HsConfig.theme) {
This is not used anymore. I just forgot to delete

2020-11-25 16:16 UTC, FilipLeitner approved these changes

2020-11-25 17:27 UTC, merged