Draw login warning + name in compositon schema
hslayers/hslayers-ng pull request #1302
Opened 2020-11-30 13:37 UTC by FilipLeitner

2020-12-03 19:40 UTC, jmacura requested changes

2020-12-03 20:39 UTC, FilipLeitner commented on components/datasource-selector/micka/micka-filters.service.ts
> +  suggestionsModalVisible: boolean;
I guess I wanted to minimize number of dom modifications. So if youd once created micka "advanced search" modal you dont have to remove and recreate it the second time you opening it. Same applies to "suggestions" modal. Service was way to go.
But if we prefer the second approach of add/remove I can just quickly change those

2020-12-03 20:54 UTC, jmacura commented on components/datasource-selector/micka/micka-filters.service.ts
> +  suggestionsModalVisible: boolean;
Ack. If you expect it to be faster, then let's keep it that way.

2020-12-07 13:27 UTC, jmacura requested changes
A tremendous amount of errors in my console, but... yeah... from the user point of view it all works 🙂 

Please, correct the typo and the `log` and it's good to go 👍

2020-12-07 13:27 UTC, jmacura commented on components/compositions/compositions.service.ts
> +    console.log(ds)
```suggestion
```

2020-12-07 16:44 UTC, jmacura approved these changes

2020-12-08 16:35 UTC, merged