refactor: Use new filtering params forLayman requests in compositions…
hslayers/hslayers-ng pull request #1777
Opened 2021-04-28 12:19 UTC by DailisLangovskis

… component

2021-04-28 23:04 UTC, raitisbe commented on projects/hslayers/src/components/compositions/endpoints/compositions-layman.service.ts
> +    if (!response.body && response.body.length == 0) {
Can both conditions even be true at the same time?

2021-04-29 06:26 UTC, FilipLeitner commented
Have seen it already and discussed with Dailis, theres a fix needed because Layman layers are not visible when onlyMine filter is false

2021-04-29 18:12 UTC, FilipLeitner commented
Keep thinking about the "filter by map extent"  and "sort by BBOX" interaction. Dont think that user will understand  what it means or know what to do when a error message " Value "bbox" of parameter "order_by" can be used only if "bbox_filter" or "bbox" parameter is set." pop up. 
We could either disable this combination  or at least we should make the message more explanatory from the user point of view.
What do you think?

2021-04-29 19:03 UTC, DailisLangovskis commented
> Keep thinking about the "filter by map extent" and "sort by BBOX" interaction. Dont think that user will understand what it means or know what to do when a error message " Value "bbox" of parameter "order_by" can be used only if "bbox_filter" or "bbox" parameter is set." pop up.
> We could either disable this combination or at least we should make the message more explanatory from the user point of view.
> What do you think?

Hmm.. mby we should create a dialog to inform the user and ask if user wants to enable filter by extent to continue.

2021-04-30 15:45 UTC, DailisLangovskis commented on projects/hslayers/src/components/add-data/catalogue/micka/micka.service.ts
> +          ? 'date:D'
No I actually did this on purpose.

2021-04-30 22:17 UTC, jmacura requested changes
I propose some polishing of translations (grammar nazi 👮 😳 )

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "mapExtentFilterMissing": "Řazení výsledku dle rozsahu dat je možné jenom po aktivaci 'filtrace na rozsah okna'. Aktivujte jej prosím.",
```suggestion
    "mapExtentFilterMissing": "Řazení výsledků dle rozsahu dat je možné jen po aktivaci 'filtrace na rozsah okna'. Aktivujte ji prosím.",
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "unknownError": "Neznáma chyba. Zkuste to znova, prosím.",
```suggestion
    "unknownError": "Neznámá chyba. Zkuste to znovu, prosím.",
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "Unsuccessful OAuth2 authentication. Access token is not valid": "Neuspešná autentizace. Neplatný přístupový token"
```suggestion
    "Unsuccessful OAuth2 authentication. Access token is not valid": "Neúspěšná autentizace OAuth2. Neplatný přístupový token"
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "0": "Chybná odpověď pro {{url}}: 0 Neznáma chyba",
```suggestion
    "0": "Chybná odpověď pro {{url}}: 0 Neznámá chyba",
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "400": "Chybná odpověď pro {{url}}: 400 Nesprávny požadavek",
```suggestion
    "400": "Chybná odpověď pro {{url}}: 400 Špatný požadavek",
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "502": "Chybná odpověď pro {{url}}: 502 Nesprávna brána",
```suggestion
    "502": "Chybná odpověď pro {{url}}: 502 Špatná brána",
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +    "Invalid Params": "Před sdílením mapy se ujistete zdali jsou všechna vyžadována pole správne vyplnená!"
```suggestion
    "Invalid Params": "Před sdílením mapy se ujistěte zda jsou všechna vyžadovaná pole správně vyplněná!"
```

2021-04-30 22:17 UTC, jmacura commented on projects/hslayers/src/assets/locales/en.json
> +    "mapExtentFilterMissing": "Please enable Filter by map extent checkbox to by able to sort data by Bounding box",
```suggestion
    "mapExtentFilterMissing": "Please enable Filter by map extent checkbox to be able to sort data by Bounding box",
```

2021-05-01 08:19 UTC, FilipLeitner commented
> I propose some polishing of translations (grammar nazi 👮 😳 )

Great, thanks! Struggled a with some of them so I hoped something like this would come

2021-05-07 08:19 UTC, raitisbe approved these changes

2021-05-07 08:20 UTC, merged