Versions update, Layer manager extension
hslayers/hslayers-ng pull request #1998
Opened 2021-07-14 10:59 UTC by SLeitgeb

2021-07-25 20:35 UTC, raitisbe requested changes

2021-07-25 20:35 UTC, raitisbe commented on package.json
> +    "prettier": "^2.3.1",
Prettier seems to be listed twice

2021-07-25 20:35 UTC, raitisbe commented on projects/hslayers-material/package.json
> +    "hslayers-ng": "^4.0.1"
Can target 5 now

2021-08-10 10:02 UTC, SLeitgeb commented
Added an option to specify layout widths with percentage values in d05b2ecbd5861b96145bc789dff7edb6c4bc7d77

2021-08-10 10:57 UTC, raitisbe approved these changes

2021-08-10 10:59 UTC, raitisbe commented
Thank you. Just a quick thing before merge, could you rename the commits and squash some of them if possible to follow https://www.conventionalcommits.org/en/v1.0.0/ standard?

2021-08-10 12:57 UTC, SLeitgeb commented
This should be much better hopefully! Thanks for the link, I was wondering where those neat commit messages came from :)

2021-08-10 17:35 UTC, raitisbe commented
> This should be much better hopefully! Thanks for the link, I was wondering where those neat commit messages came from :)

You can also create the commit with `npm run commit` using a wizard ;)

2021-08-10 17:35 UTC, merged