feat: Widget for setting bounds and colormap for IDW layer
hslayers/hslayers-ng pull request #3068
Opened 2022-05-30 22:48 UTC by raitisbe

## Description

A widget in layer editor which allows setting attribute which to visualize, color map and value interval in which to visualize
![image](https://user-images.githubusercontent.com/395514/171065677-07e0f7d5-baec-4a6b-84eb-3cd773b9722e.png)

## Related issues or pull requests

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [ ] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

2022-06-01 07:07 UTC, DailisLangovskis requested changes
Sometimes, when changing the IDW layer, IDW widget min max values, for example, (1-50), idw layer is coloured in one color only, with no change when zooming or panning the map.

When reloading the page, feature attributes dropdown is empty.

2022-06-01 08:46 UTC, raitisbe commented
> Sometimes, when changing the IDW layer, IDW widget min max values, for example, (1-50), idw layer is coloured in one color only, with no change when zooming or panning the map.

If the actual values are in the thousands or millions, it can happen yes, but its not wrong imho

2022-06-02 10:08 UTC, DailisLangovskis approved these changes
Everything looks good, only thing I would remove hs_normalized_IDW_value fro list of numeric attributes, because it is generated from real data attributes anyway.

P.S. Code descriptions and input types would be good to have as well. :)

2022-06-02 10:51 UTC, raitisbe commented
> hs_normalized_IDW_value

good point

2022-06-02 11:27 UTC, merged