Fixes filip 11 1
hslayers/hslayers-ng pull request #3783
Opened 2023-02-07 14:08 UTC by FilipLeitner

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [ ] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

2023-02-07 16:19 UTC, jmacura commented on projects/hslayers/src/components/query/query-wmts.service.ts
> +  ) { }
lint

2023-02-07 16:19 UTC, jmacura commented on projects/hslayers/src/components/query/query-wmts.service.ts
> +  ): Promise<{ url: string; format: string }> {
lint

2023-02-07 16:19 UTC, jmacura commented on projects/hslayers/src/components/save-map/interfaces/layman-layer-descriptor.interface.ts
> +  //Not part of origial response. Added by describeLayer
```suggestion
  /**
   * Not part of origial response. Added by describeLayer
   */
```

2023-02-14 21:46 UTC, jmacura requested changes
Default imports are not tree-shakeable and were causing some issues with federated modules (see https://github.com/hslayers/hslayers-ng/pull/3514)

I have already done the change, no action needed from you @FilipLeitner in this matter.

2023-02-14 21:50 UTC, jmacura approved these changes

2023-02-14 21:53 UTC, jmacura commented
Code-wise the change is fine with me. Thanks again for all the fixes!

I have tested the functionality and there is one missing imperfection regarding #3764 related changes. When I add WFS layer from an external source (via Add Data -> URL), the layer is not zoomed in, while when I add the same layer from Data Catalogue, it does zoom correctly.

2023-02-14 22:06 UTC, jmacura commented
> (...) When I add WFS layer from an external source (via Add Data -> URL), the layer is not zoomed in, while when I add the same layer from Data Catalogue, it does zoom correctly.

Ah, hint 😄 https://github.com/hslayers/hslayers-ng/blob/ac50d6156d5a2b94fd830f67dc055e0cc275e6d7/projects/hslayers/src/components/add-data/common/url/add/add.component.ts#L53

2023-02-15 08:02 UTC, FilipLeitner commented
Oh sure, I tunnelled hard just on the file upload. I will fix this as well :)

2023-02-15 18:59 UTC, FilipLeitner commented
Took much longer than expected. WFS and WMS seem to be working fine.  Rest of the layer types tbd

2023-02-15 19:49 UTC, jmacura reviewed
Some minor typos again, but good to go from my POV.

Thanks for the improvement

2023-02-15 19:49 UTC, jmacura commented on projects/hslayers/src/components/add-data/url/add-data-url.service.ts
> +    private hsMapsService: HsMapService
```suggestion
    private hsMapService: HsMapService
```
With code-completion, this is not that much of a issue, but could be misleading..

2023-02-15 19:49 UTC, jmacura commented on projects/hslayers/src/components/add-data/url/wfs/wfs.service.ts
> +   * Zoom map to one layers or combined layer list extent
```suggestion
   * Zoom map to one layer or combined layer list extent
```

2023-02-15 19:49 UTC, jmacura commented on projects/hslayers/src/components/add-data/url/wms/wms.service.ts
> +          boundingbox[0].crs || crs, //Use BBOX object crs - when missing assume its same as layer's
```suggestion
          boundingbox[0].crs || crs, //Use BBOX object crs - when missing assume it's same as layer's
```

2023-02-15 19:49 UTC, jmacura commented on projects/hslayers/src/components/query/query-wms.service.ts
> +       * TODO: Layered response need to be refactored as well but I havent found and example yet
```suggestion
       * TODO: Layered response need to be refactored as well but I haven't found an example yet
```

2023-02-17 09:32 UTC, merged