Wms type widget
hslayers/hslayers-ng pull request #4528
Opened 2023-11-30 11:15 UTC by FilipLeitner

## Description
- add third add-data option WMTS - which is actually old WMS option (tiled WMS) while, new WMS option creates Image WMS layer
<img width="434" alt="image" src="https://github.com/hslayers/hslayers-ng/assets/44566616/cfaf463a-20ab-4877-81f3-e45c17b1f9e9">

- add layer-editor widget allowing switching between the types
<img width="625" alt="image" src="https://github.com/hslayers/hslayers-ng/assets/44566616/57bbafb0-9375-40cf-a9be-8252e9cc425c">

## Related issues or pull requests

https://github.com/hslayers/hslayers-ng/issues/4497

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

2023-11-30 23:59 UTC, jmacura requested changes

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/components/layermanager/widgets/wms-source-widget/wms-source-widget.component.ts
> +   * Clone layer properties and oarmeters and recreate it as a different type
```suggestion
   * Clone layer properties and parameters and recreate it as a different type
```

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/components/layermanager/widgets/wms-source-widget/wms-source-widget.component.css
Can be deleted, right?

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/assets/locales/en.json
> +        "WMTS": "Web Map Tile Service - serves raster images simillarliy to WMS . The difference is that tile service serves content divided into 'tile' which are loaded individually - thus being pot
```suggestion
        "WMTS": "Web Map Tile Service - serves raster images similarly to WMS. The difference is that tile service serves content divided into 'tiles' which are loaded individually - thus being potentially more performant."
```

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
>          "WFS": "Web Feature Service - stahovací: slouží pro práci s geografickými daty ve vektorové reprezentaci. Je výkonostne naročnejší, především při rozsáhlejších vrstvách, umožňuje však editaci
```suggestion
        "WFS": "Web Feature Service - stahovací: slouží pro práci s geografickými daty ve vektorové reprezentaci. Je výkonnostně náročnejší, především při rozsáhlejších vrstvách, umožňuje však editaci či zobrazení individuálních informací ke každému prvku zvlášť.",
```

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +        "WMS": "Web Map Service - prohlížecí: data nahraje v podobě rastru. Přenášená data jsou obvykle menší co má za následek rychlejší načítání, no na druhou stranu ich není možné upravovat.",
```suggestion
        "WMS": "Web Map Service - prohlížecí: data načte v podobě rastru. Přenášená data jsou obvykle menší, což má za následek rychlejší načítání. Na druhou stranu, načtené prvky nelze upravovat.",
```

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/assets/locales/cs.json
> +        "WMTS": "Web Map Tile Service - slouží pro rastrové obrázky podobně jako WMS . Rozdíl je v tom, že dlaždicová služba slouží pro obsah rozdělený do \"dlaždic\", které se načítají jednotlivě -
```suggestion
        "WMTS": "Web Map Tile Service - slouží pro rastrové obrázky podobně jako WMS. Rozdíl je v tom, že dlaždicová služba slouží pro obsah rozdělený do \"dlaždic\", které se načítají jednotlivě - je tedy potenciálně výkonnější."
```

2023-11-30 23:59 UTC, jmacura commented on projects/hslayers/src/components/layermanager/widgets/wms-source-widget/wms-source-widget.component.ts
> +export class WmsSourceWidgetComponent extends HsLayerEditorWidgetBaseComponent {
```suggestion
export class HsWmsSourceWidgetComponent extends HsLayerEditorWidgetBaseComponent {
```

2023-12-01 09:01 UTC, FilipLeitner commented on projects/hslayers/src/components/layermanager/widgets/wms-source-widget/wms-source-widget.component.ts
> +export class WmsSourceWidgetComponent extends HsLayerEditorWidgetBaseComponent {
[6d1a9cd](https://github.com/hslayers/hslayers-ng/pull/4528/commits/6d1a9cd32eb8580cef062c368a9411c281c3a5e2)

2023-12-01 09:07 UTC, FilipLeitner commented
One important change we have agreed on with @fzadrazil 

User doesnt have to go through layer type options(WMS,WMTS,WFS)  anymore.
Cliking 'Add to map' button adds map as a 'Tiled WMS' right away
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/76a543fd-e8ac-401b-b1e2-06070c8f0c6d)

Options are still avaialble but only after clicking on 'dropdown' icon. Thinking whether this little button is not too subtle when not highlighted. I mean it should be just an advanced option for some users but still
![image](https://github.com/hslayers/hslayers-ng/assets/44566616/85663e0c-fb7e-40d5-b4cf-0cb4b7ae0bf5)

2023-12-01 09:33 UTC, jmacura commented
> One important change we have agreed on with @fzadrazil
> 
> User doesnt have to go through layer type options(WMS,WMTS,WFS) anymore. Cliking 'Add to map' button adds map as a 'Tiled WMS' right away ![image](https://private-user-images.githubusercontent.com/44566616/287216040-76a543fd-e8ac-401b-b1e2-06070c8f0c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMwOTYsIm5iZiI6MTcwMTQyMjc5NiwicGF0aCI6Ii80NDU2NjYxNi8yODcyMTYwNDAtNzZhNTQzZmQtZThhYy00MDFiLWIxZTItMDYwNzBjOGYwYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OGY4YTQwZmZlOGQyNmQ2NzQ2YzM3ZWM1OTg0NTc2ZjhhMWI4NzNmZGZiOTFkZjc4MTdiNmMxOWRjM2U4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJRrUwluOBXkO1-MlsRYcGPNa6JmXVqIl3OtUhjqyuI)
> 
> Options are still avaialble but only after clicking on 'dropdown' icon. Thinking whether this little button is not too subtle when not highlighted. I mean it should be just an advanced option for some users but still ![image](https://private-user-images.githubusercontent.com/44566616/287216223-85663e0c-fb7e-40d5-b4cf-0cb4b7ae0bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMwOTYsIm5iZiI6MTcwMTQyMjc5NiwicGF0aCI6Ii80NDU2NjYxNi8yODcyMTYyMjMtODU2NjNlMGMtZmI3ZS00MGQ1LWI0Y2YtMGNiNGI3YWUwYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNDBmMGQzMjVhYmYxMmVhMDFjZjRiNDY2Yjk4YThhYTExNzUxM2E4YjI3M2E2MTJkY2FlNzEzZGZiNGI0NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9JAeQDl-pOKNAmoSKlcZ9CVNhZsUGrC1TIceHaXPLM)

I am in favour of this change :+1: But my comment goes to the down arrow mentioned. I think it is too subtle and would use the common up/down arrows used elsewhere in the app, i.e.
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/cfca47a0-27b8-4aaa-bfd4-9becd16e105a)

Also, the question sign and red cross icons are misaligned in the "advanced" line. Seems like they float too high. Can you do something about them?

2023-12-01 09:58 UTC, jmacura commented
Alternatively, I can imagine a UI like this:
![image](https://github.com/hslayers/hslayers-ng/assets/5598693/bcb79da4-f721-420b-a92b-be03289c4f5f)
WMTS (or TileWMS..?) would be pre-selected, advanced users could switch the option with the dropdown. It has the advantage that you always know what type of service you are adding. But not sure where to put the question sign help in this case... 🤔 

Just an idea, take it or leave it ;-) @FilipLeitner @fzadrazil

2023-12-01 18:22 UTC, fzadrazil commented
> One important change we have agreed on with @fzadrazil
> 
> User doesnt have to go through layer type options(WMS,WMTS,WFS) anymore. Cliking 'Add to map' button adds map as a 'Tiled WMS' right away ![image](https://private-user-images.githubusercontent.com/44566616/287216040-76a543fd-e8ac-401b-b1e2-06070c8f0c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTQ5MjgsIm5iZiI6MTcwMTQ1NDYyOCwicGF0aCI6Ii80NDU2NjYxNi8yODcyMTYwNDAtNzZhNTQzZmQtZThhYy00MDFiLWIxZTItMDYwNzBjOGYwYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE4MTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOWQ0ODg2ZjAzNzYzNTVkNzlmNWE0NjY0Y2M1NjliZmQ0ODhlYzM2NWY3ZTgzOWUwMTgzNmRkMWMzYmIyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1iSEJP6bgc3W8UpH86LXFM39yj9n6odaYI9re1Had9w)
> 
Yes, it is too subtle and I agree with Jan that the chevron would be better 
![image](https://github.com/hslayers/hslayers-ng/assets/48727502/31ae8b70-ea4a-4071-9a0a-8fdd1fb252ce)

I would set WMS as default option, not TiledWMS. WMS is fine for most cases and tiles can cause some ugly issues when not used properly.

2023-12-04 12:33 UTC, jmacura approved these changes
Thanks, great change!

2023-12-04 12:39 UTC, merged