Issue 903/custom panels
hslayers/hslayers-ng pull request #936
Opened 2020-08-19 20:53 UTC by raitisbe

2020-08-19 22:01 UTC, jmacura commented
Great! I will try to look at this tomorrow.

2020-08-20 13:46 UTC, raitisbe commented
@jmacura See https://github.com/hslayers/project-rostenice/commits/upgrade-hslayers-2

2020-08-20 20:33 UTC, jmacura commented
![image](https://user-images.githubusercontent.com/5598693/90822721-26167800-e335-11ea-99fa-b6cd86a74ecb.png)

![image](https://user-images.githubusercontent.com/5598693/90822743-2f9fe000-e335-11ea-8c6b-593fe6a3fdbc.png)

Awesome!

2020-08-20 20:51 UTC, jmacura commented
It works just charmingly 😋 
![image](https://user-images.githubusercontent.com/5598693/90824308-81496a00-e337-11ea-98b2-2b347c7a6f1d.png)
![image](https://user-images.githubusercontent.com/5598693/90824326-8d352c00-e337-11ea-8db6-b7d6073ebbf4.png)
![image](https://user-images.githubusercontent.com/5598693/90824341-932b0d00-e337-11ea-9260-65f0f94d1261.png)

2020-08-20 21:10 UTC, jmacura requested changes
Following our current naming practice, I propose to rename `panel-component.ts` to `panel-component.interface.ts`
and `panel-item.class.ts` to `panel-item.ts`
(reasoning behind that: basically everything is a class now -- all components, services or modules -- but just a few files define interfaces)

**Some general questions:**
Why have you decide to make default panels have `ng-show="panelVisible('name', this)">` defined in the layout.html template, but custom panels must implement the `ng-show` (or `[hidden]`) independently via `isVisible()`?

What is the intended usage of the `data` property in the custom HsPanelComponent?

2020-08-20 21:10 UTC, jmacura commented on components/layout/panels/panel-component.ts
> +  isVisible();
add boolean as a required return value type

2020-08-20 21:10 UTC, jmacura commented on components/layout/panels/panel-item.class.ts
> +/*
I feel like the following lines can be safely deleted 😉

2020-08-20 21:52 UTC, raitisbe commented
> Why have you decide to make default panels have `ng-show="panelVisible('name', this)">` defined in the layout.html template, but custom panels must implement the `ng-show` (or `[hidden]`) independently via `isVisible()`?
> 
Not so much that I did decide, more like I could not find a way how to set the ng-show from outside (from the container component). isVisible in the interface is just so all the components would follow more or less the same principle how to toggle themselves on/off.

2020-08-20 21:58 UTC, raitisbe commented
> What is the intended usage of the `data` property in the custom HsPanelComponent?

Pretty much leftover from dialog component, but there are hypothetical use cases, for example having 2 instances of the same panel with various headings or something such.

2020-08-20 22:25 UTC, jmacura approved these changes

2020-08-20 22:28 UTC, jmacura commented
> 
> 
> > Why have you decide to make default panels have `ng-show="panelVisible('name', this)">` defined in the layout.html template, but custom panels must implement the `ng-show` (or `[hidden]`) independently via `isVisible()`?
> 
> Not so much that I did decide, more like I could not find a way how to set the ng-show from outside (from the container component). isVisible in the interface is just so all the components would follow more or less the same principle how to toggle themselves on/off.

I see. Good choice then, to define the method in the interface.

2020-08-21 08:48 UTC, merged